Create patch set 2
Uploaded patch set 2.

Outdated Votes:
* Open-Source-Licensing+1 (copy condition: "changekind:NO_CODE_CHANGE OR changekind:TRIVIAL_REBASE OR is:MIN")
* Presubmit-Ready+1 (copy condition: "**is:MAX** AND (changekind:NO_CODE_CHANGE OR changekind:TRIVIAL_REBASE)")


Patch-set: 2
Subject: capture NoClassDefFoundError
Commit: fc3d31bcc4253123e87ea25c2fc185fe29317a51
Tag: autogenerated:gerrit:newPatchSet
Groups: fc3d31bcc4253123e87ea25c2fc185fe29317a51
Attention: {"person_ident":"Gerrit User 1944425 \u003c1944425@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"ADD","reason":"Vote got outdated and was removed: Presubmit-Ready+1"}