Use ZipInfo.is_dir() instead of unix_filetype.
unix_filetype is obtained from ZipInfo.external_attr. If the target-files are repackaged, external_attr may be set incorrectly, the dir will be identified as a file, and the 0o644 permissions will be set, resulting in no permission to create files in the dir, like this:
File "ota_utils.py", line 729, in ExtractTargetFiles
File "common.py", line 2186, in UnzipToDir
File "common.py", line 2122, in UnzipSingleFile
File "internal/stdlib/zipfile.py", line 1624, in extract
File "internal/stdlib/zipfile.py", line 1695, in _extract_member
PermissionError: [Errno 13] Permission denied: '/tmp/target_files0l6z_l3h/VENDOR/odm/etc/vintf/xxx'

Although repackaging target-files is not a common operation, it is recommended to use ZipInfo.is_dir() instead of unix_filetype.

Change-Id: I9200b7455d0777804582e14a398dcbbd74fae115